apiVersion: v1
kind: ServiceAccount
metadata:
    name: default
    namespace: frontend-dev
imagePullSecrets:
    - name: aws-ecr-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: backend-dev
imagePullSecrets:
    - name: aws-ecr-auth